// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zksgfrsmdxijulhfrgpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprc2dmcnNtZHhpanVsaGZyZ3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDYxMTYsImV4cCI6MjA2NjUyMjExNn0.vDJBnLH5qpVGu42zwS12Op7im7EHJcSZ4IKOeiYqhyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);